### PR TITLE
Prow vm secret

### PR DESCRIPTION
**Pull request by jakkab**
test

### CODE REVIEW

**Comment by jakkab** [comment]
@jakkab: [cat image](https://thecatapi.com/?image_id=2dg)

<details>

In response to [this](https://github.com/jakkab/kyma/pull/10#issuecomment-434638806):

>/meow


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jakkab** [comment]
@jakkab: Two peanuts were walking down the street. One was a salted

<details>

In response to [this](https://github.com/jakkab/kyma/pull/10#issuecomment-434673977):

>/joke


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jakkab** [comment]
@jakkab: [cat image](https://thecatapi.com/?image_id=ma)

<details>

In response to [this](https://github.com/jakkab/kyma/pull/10#issuecomment-435836364):

>/meow


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jakkab** [comment]
@jakkab: Why is the ocean always blue? Because the shore never waves back.

<details>

In response to [this](https://github.com/jakkab/kyma/pull/10#issuecomment-436216820):

>/joke


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jakkab** [comment]
@sjanota: Why did the barber win the race? He took a short cut.

<details>

In response to [this](https://github.com/jakkab/kyma/pull/10#issuecomment-436219541):

>/joke
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jakkab** [comment]
@sjanota: [cat image](https://thecatapi.com/?image_id=3tb)

<details>

In response to [this](https://github.com/jakkab/kyma/pull/10#issuecomment-436219576):

>/meow


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jakkab** [comment]
@jakkab: [cat image](https://thecatapi.com/?image_id=4jk)

<details>

In response to [this](https://github.com/jakkab/kyma/pull/10#issuecomment-439374419):

>/meow


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by sapjk** [comment]
🦉🚽🔶🛁⬇

**Pull request closed without merging**
